FROM mambaorg/micromamba:0.15.2

COPY --chown=micromamba:micromamba environment-cpu.yml /tmp/env.yml
RUN micromamba install -y -n base -f /tmp/env.yml && \
    micromamba clean --all --yes

RUN python -m pip install .

USER root
