FROM cmelab/gpuhoomdconda:latest

# Create the environment
COPY environment-nohoomd.yml ./

# Install in base environment
RUN conda install -y -n base -c conda-forge git && \
	conda env update -n base -f environment-nohoomd.yml && \
    conda clean --all --yes -f 

COPY uli_init/ ./uli/uli_init/

COPY setup.py ./uli/

RUN python -m pip install ./uli
