FROM mambaorg/micromamba:0.15.2

COPY --chown=micromamba:micromamba environment-cpu.yml /tmp/env.yml
RUN micromamba install -y -n base -f /tmp/env.yml && \
    micromamba clean --all --yes

COPY uli_init/ ./uli/uli_init/

COPY setup.py ./uli/

RUN ls -la ./uli

RUN python -m pip install ./uli

RUN pytest

USER root
