FROM cmelab/gpuhoomdconda:latest

# Create the environment
COPY environment-nohoomd.yml ./

# Install in base environment
RUN conda install -y -n base -c conda-forge git && \
	conda env update -n base -f environment-nohoomd.yml && \
    conda clean --all --yes -f 

COPY polybinder/ ./polybinder/polybinder/

COPY setup.py ./polybinder/

RUN python -m pip install ./polybinder
