name: pytest

on:
  push:
    # Action will run when any changes to these paths are pushed or pr'ed to master
    branches: [ master ]
    paths:
      - 'uli_init/*'
      - 'uli_init/tests/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'uli_init/*'
      - 'uli_init/tests/*'
  # Allows workflow to be manually triggered
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest
    container: 
        image: cmelab/uliinit_cpu:latest

    steps:
    - uses: actions/checkout@v2
 
    - name: Run pytest with coverage report
      run: python -m pytest -rs -v --cov=./ --cov-report=xml
          
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
